# Generated by Django 6.0.2 on 2026-02-25 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom del Club')),
                ('provincia', models.CharField(max_length=100, verbose_name='Província')),
                ('regio', models.CharField(max_length=100, verbose_name='Comunitat Autònoma')),
                ('pais', models.CharField(default='Espanya', max_length=100, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_i_cognoms', models.CharField(max_length=200, verbose_name='Nom i Cognoms')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_jugadors/', verbose_name='Foto')),
                ('elo_fide', models.IntegerField(default=0, verbose_name='ELOFIDE')),
                ('elo_regio', models.IntegerField(default=0, verbose_name='ELOREG')),
                ('id_fide', models.IntegerField(default=0, verbose_name='IDFIDE')),
                ('id_regio', models.IntegerField(default=0, verbose_name='IDREG')),
                ('sexe', models.CharField(choices=[('M', 'Masculí'), ('F', 'Femení'), ('O', 'Other')], max_length=1, verbose_name='Sexe')),
                ('data_naixement', models.DateField(verbose_name='Data de naixement')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.club', verbose_name='Club')),
                ('pujat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
