# Generated by Django 6.0.2 on 2026-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Categoria (Senior)'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='titol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Títol (GM, IM...)'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nom',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom del Club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='pais',
            field=models.CharField(blank=True, default='Espanya', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='club',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='club',
            name='regio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comunitat Autònoma'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='data_naixement',
            field=models.DateField(blank=True, null=True, verbose_name='Data de naixement'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='elo_fide',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ELOFIDE'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='elo_regio',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ELOREG'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id_fide',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='IDFIDE'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id_regio',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='IDREG'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculí'), ('F', 'Femení'), ('O', 'Other')], max_length=1, null=True, verbose_name='Sexe'),
        ),
    ]
