# Generated by Django 6.0.2 on 2026-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jugador_categoria_jugador_titol_alter_club_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria (Senior,...)'),
        ),
    ]
